---
# tasks file for k8s_slave

- name: "Installing docker"
  package:
     name: "docker"
     state: present

- name: " Start docker service "
  service:
     name: "docker"
     state: started
     enabled: yes

- name: "Configuring yum repo for kubernetes"
  yum_repository:
     baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
     name: "Kubernetes_Repolist"
     description: "Yum Repo For Kubernetes"
     gpgcheck: yes
     gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
     repo_gpgcheck: yes
     enabled: yes

- name: " Install kubelet , kubeadm , kubectl softwares "
  package:
      name: "{{ packages }}"
      state: present
      update_cache: yes

- name: "Starting and enabling kubelet service permanently"
  service:
      name: "kubelet"
      state: started
      enabled: yes


- name: "Changing the Driver"
  copy:
      src: "/etc/ansible/roles/slaves/files/docker_daemon.json"
      dest: "/etc/docker/daemon.json"
  register: driver_output

- name: "Restarting docker service"
  service:
      name: "docker"
      state: restarted

- debug:
      var: driver_output

- name: "Installing iproute-tc "
  package:
            name: "iproute-tc"
            state: present

- name: "Setting bridge-nf-call-iptables to 1"
  shell: |
       echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables
  changed_when: false

- name: "Connect the k8s_Slave to Master"
  shell: "{{ token }}"
  ignore_errors: yes
  register: connected

- debug:
     var: connected
